# 链接样式，参考 http://jekyllrb.com/docs/permalinks
permalink: /:categories/:year-:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
paginate: 5

markdown: redcarpet             # markdown 语法解释引擎
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
# 参考 http://github.com/vmg/redcarpet/blob/master/README.markdown

# 核心设置
title : 天天向上
tagline: 好好学习，天天向上...
keywords : linux ,machine learning ,data mining , R , Hadoop ,Spark
description: 好好学习，天天向上...
author :
  name :  mlhadoop
  email : 
  github : mlhadoop
  gitcafe : 
  twitter :
  facebook :  mlhadoop
  feedburner :
  weibo : mlhadoop

# 域名连接
production_url : http://daydayuper.vicp.net

# 七牛云，http://<Bucket>.qiniudn.com
qiniudn: //havee.qiniudn.com



# Jekyll Bootstrap
JB :
  version : 0.3.0

  BASE_PATH : false                 # 如果不懂参数，请不要更改
  ASSET_PATH : false                # 同上

  # page
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # 评论，provider 留空或 false 关闭评论
  comments :
    provider :    duoshuo                  # 采用那种评论，可填 duoshuo 或 disqus 或其他 ...
    disqus :
      short_name :
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width: 580
      colorscheme: light
    duoshuo :
      name :  dcy123             # 多说上获取的 shortname
      rcomments :                   # 首页侧边栏最新评论
        num: 10                     # 最新评论显示条数
        avatar : 0                  # 最新评论是否显示头像
        time: 0
        title : 0
        admin : 0
        length : 12                 # 最新评论显示的长度
      rvisitors :                   # 首页侧边栏最新访客
        num : 12                    # 最新访客数目
        size : 45                   # 最新访客头像的尺寸

  # 网站统计
  analytics :
    provider :                      # 采用那种统计，可填 baidu 或 google 或其他 ...
    google :
        tracking_id : 'UA-53828211-1'
    getclicky :
        site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
    baidu :
        siteid:         # 百度统计 js 代码后的字符串
        

  # 一键分享
  sharing :
    provider :   baidu                   # 参考 _includes/JB/sharing

  

  # 友情链接
  blogroll : false                   # true 开启，留空或 false 关闭
  brlist :
    - text : 
      url : 
